"""empty message

Revision ID: 28bfaa498509
Revises: None
Create Date: 2015-10-20 02:40:07.303000

"""

# revision identifiers, used by Alembic.
revision = '28bfaa498509'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.add_column('track', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('track', sa.Column('upvote', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'upvote')
    op.drop_column('track', 'downvote')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    ### end Alembic commands ###
