"""empty message

Revision ID: 437855d3b3f0
Revises: None
Create Date: 2015-10-21 00:36:13.148000

"""

# revision identifiers, used by Alembic.
revision = '437855d3b3f0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('upvote_flag', sa.Integer(), nullable=False),
    sa.Column('downvote_flag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.alter_column(u'track', 'downvote',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text(u'0'))
    op.alter_column(u'track', 'upvote',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'track', 'upvote',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column(u'track', 'downvote',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text(u'0'))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_table('trackvote')
    ### end Alembic commands ###
